Algoritmo "semnome"
// Data atual  : 06/09/2023
Var
// Seção de Declarações das variáveis 
  contador, numero: inteiro
  nome_equipe: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... ]
     EscrevaL("     Torneio de e-sports     ")
     EscrevaL("Insira o nome da sua quipe: ")
     Leia(nome_equipe)
     Para contador de 1 ate 5 faca
          EscrevaL(nome_equipe," - ", contador, "°")
     FimPara

Fimalgoritmo